### ISSUE TITLE
Windows release?

### ISSUE THREAD

**Issue by gd4c** [sile/funst#1]
funst seems like a nice quick statistics tool. Could you please make a release for Windows?

**Comment by sile** [comment]
Thank you for reaching out.
It sounds cool!
I don't know how to make a Windows build now, but I'd like to investigate it and release the binary in the near future.

**Comment by gd4c** [comment]
That would be great. Thanks!

**Comment by sile** [comment]
I added Windows release support by #2.
The latest release binary can be found [here](https://github.com/sile/funst/releases/tag/0.1.1).

**Comment by gd4c** [comment]
Can confirm it working. Thanks a lot!
